"""End-to-end tests for the One-click working step (``ui.step_one_click``).

The One-click step takes two inputs - domain + systems - and a single
Generate click runs the whole pipeline and lands on the dashboard. These
tests drive the real widgets through ``AppTest`` and assert on the
resulting session state (auto-built config, scorecards, summary banner) and
the validation gating.
"""
from __future__ import annotations

import os
from pathlib import Path

os.environ.setdefault("DATA_SOURCE", "mock")

from streamlit.testing.v1 import AppTest  # noqa: E402

from config.dqr_sources import SOURCE_CUSTOM, SOURCE_STANDARD  # noqa: E402

APP_PATH = str(Path(__file__).resolve().parent.parent / "app.py")


def _one_click_app(**state) -> AppTest:
    """An app sitting on the One-click step (One-click mode active)."""
    at = AppTest.from_file(APP_PATH, default_timeout=60)
    at.session_state["app_mode"] = "one_click"
    at.session_state["current_step"] = "one_click"
    for k, v in state.items():
        at.session_state[k] = v
    at.run()
    return at


# ---------------------------------------------------------------------------
# Rendering + picker reveal
# ---------------------------------------------------------------------------

def test_renders_domain_picker_with_cards():
    at = _one_click_app()
    keys = [b.key for b in at.button]
    assert "oneclick_domain_cost_estimate" in keys
    assert "oneclick_domain_quality" in keys
    # No systems yet (no domain picked) -> no system checkbox.
    assert not any(c.key.startswith("oneclick_sys_") for c in at.checkbox)


def test_picking_domain_reveals_systems():
    at = _one_click_app()
    at.button(key="oneclick_domain_cost_estimate").click().run()
    assert at.session_state["domain"] == "cost_estimate"
    sys_keys = [c.key for c in at.checkbox if c.key.startswith("oneclick_sys_")]
    assert "oneclick_sys_EPT" in sys_keys
    assert "oneclick_sys_ADR" in sys_keys


# ---------------------------------------------------------------------------
# Validation gating
# ---------------------------------------------------------------------------

def test_generate_disabled_without_domain():
    at = _one_click_app()
    gen = at.button(key="oneclick_generate")
    assert gen.disabled
    assert any("Pick a domain" in m.value for m in at.markdown)


def test_generate_disabled_without_system():
    at = _one_click_app(domain="cost_estimate", selected_systems=[])
    gen = at.button(key="oneclick_generate")
    assert gen.disabled
    assert any("Select at least one system" in m.value for m in at.markdown)


# ---------------------------------------------------------------------------
# Full automated run
# ---------------------------------------------------------------------------

def test_generate_runs_pipeline_and_lands_on_dashboard():
    at = _one_click_app(domain="cost_estimate", selected_systems=["EPT"])
    gen = at.button(key="oneclick_generate")
    assert not gen.disabled
    gen.click().run()

    # Landed on the dashboard with a scored EPT data product.
    assert at.session_state["current_step"] == "dashboard"
    assert "EPT" in at.session_state["scorecards"]
    assert at.session_state["selected_systems"] == ["EPT"]

    # The auto-built config is custom-only with equal weights summing 100.
    cfg = at.session_state["configs"]["EPT"]
    assert cfg.dqr_sources == [SOURCE_CUSTOM]
    assert SOURCE_STANDARD not in cfg.dqr_sources
    assert cfg.assignments == []
    weights = [a.weight for a in cfg.custom_assignments]
    assert round(sum(weights), 2) == 100.0
    assert max(weights) - min(weights) <= 0.01


def test_generate_sets_one_click_summary_banner():
    at = _one_click_app(domain="cost_estimate", selected_systems=["EPT"])
    at.button(key="oneclick_generate").click().run()
    summary = at.session_state["one_click_summary"]
    assert summary["scored"] == ["EPT"]
    # Dashboard surfaces the One-click banner.
    assert any("Generated by One-click" in s.value for s in at.success)


def test_generate_multi_system_scores_each():
    at = _one_click_app(
        domain="cost_estimate", selected_systems=["EPT", "ADR", "ACCE"]
    )
    at.button(key="oneclick_generate").click().run()
    assert at.session_state["current_step"] == "dashboard"
    for code in ("EPT", "ADR", "ACCE"):
        assert code in at.session_state["scorecards"]


def test_back_button_returns_to_mode_picker():
    at = _one_click_app()
    back = [b for b in at.button if "Back" in b.label]
    assert back
    back[0].click().run()
    assert at.session_state["current_step"] == "mode_selection"


def test_restart_clears_and_returns_to_mode_picker():
    at = _one_click_app(domain="cost_estimate", selected_systems=["EPT"])
    # Restart is gated behind a two-click confirmation popover.
    restart = [b for b in at.button if "Yes, restart" in b.label]
    assert restart
    restart[0].click().run()
    assert at.session_state["current_step"] == "mode_selection"
    assert at.session_state["app_mode"] is None
    assert at.session_state["domain"] is None


# ---------------------------------------------------------------------------
# Validation / error-handling UI branches
# ---------------------------------------------------------------------------

def _one_click_app_no_run(**state) -> AppTest:
    """Build (but don't run) a One-click app so a monkeypatch can be applied
    before the first render."""
    at = AppTest.from_file(APP_PATH, default_timeout=60)
    at.session_state["app_mode"] = "one_click"
    at.session_state["current_step"] = "one_click"
    for k, v in state.items():
        at.session_state[k] = v
    return at


def test_no_applicable_custom_dqrs_blocks_generate(monkeypatch):
    """A selected system with no custom rules blocks Generate with a clear
    error (One-click is custom-only)."""
    import ui.step_one_click as oc_ui

    monkeypatch.setattr(oc_ui, "get_available_custom_dqr_rules", lambda code: [])
    at = _one_click_app_no_run(domain="cost_estimate", selected_systems=["EPT"])
    at.run()
    assert any("applicable Custom DQRs" in e.value for e in at.error)
    assert at.button(key="oneclick_generate").disabled


def test_generate_nothing_scored_shows_error_and_stays(monkeypatch):
    """When the pipeline scores nothing, the user stays on the step with the
    skip reasons surfaced."""
    import ui.step_one_click as oc_ui
    from src.one_click import OneClickResult

    monkeypatch.setattr(
        oc_ui, "run_one_click",
        lambda *a, **k: OneClickResult(
            domain_code="cost_estimate", requested_systems=["EPT"],
            products={}, skipped={"EPT": "the project filter matched 0 rows"},
        ),
    )
    at = _one_click_app_no_run(domain="cost_estimate", selected_systems=["EPT"])
    at.run()
    at.button(key="oneclick_generate").click().run()
    assert at.session_state["current_step"] == "one_click"  # stayed put
    assert any("could not score" in e.value for e in at.error)


def test_generate_blocking_error_keeps_user_on_step(monkeypatch):
    import ui.step_one_click as oc_ui
    from src.one_click import OneClickError

    def _boom(*a, **k):
        raise OneClickError("databricks exploded")

    monkeypatch.setattr(oc_ui, "run_one_click", _boom)
    at = _one_click_app_no_run(domain="cost_estimate", selected_systems=["EPT"])
    at.run()
    at.button(key="oneclick_generate").click().run()
    assert at.session_state["current_step"] == "one_click"
    assert any("databricks exploded" in e.value for e in at.error)


def test_generate_csv_failure_is_recorded_but_nonblocking(monkeypatch):
    """A CSV-export failure is recorded and surfaced on the dashboard but
    does not block the (valid) scorecards."""
    import ui.step_one_click as oc_ui

    def _boom_csv(*a, **k):
        raise RuntimeError("csv boom")

    monkeypatch.setattr(oc_ui, "_build_rowscores_csv", _boom_csv)
    at = _one_click_app_no_run(domain="cost_estimate", selected_systems=["EPT"])
    at.run()
    at.button(key="oneclick_generate").click().run()
    # Scorecards still generated and we still land on the dashboard.
    assert at.session_state["current_step"] == "dashboard"
    assert "EPT" in at.session_state["scorecards"]
    assert at.session_state["one_click_summary"]["csv_errors"]
    assert any("CSV export could not be prepared" in e.value for e in at.error)
