"""Section renderers for the Data Quality Report.

Top-to-bottom: sticky nav, report header (metadata grid), executive
summary, one ``<section class="dp">`` per Data Product, footer. Markup
mirrors the handoff reference (``reference/sections/*.html``) - class
names are load-bearing for the embedded CSS/JS.
"""
from __future__ import annotations

from typing import Dict, List

from config.dqr_sources import SOURCE_LABELS
from ui.step_06._rule_rows import STATUS_EVALUATED
from ui.step_06._shared import _DEFAULT_ACCENT, _SYSTEM_ACCENTS
from ui.step_06.report import tables
from ui.step_06.report.charts import gauge_svg, score_bar, stacked_bar, trend_svg
from ui.step_06.report.html import esc, fmt_int
from ui.step_06.report.models import ReportContext

_MODE_LABELS = {"one_click": "One-click", "step_by_step": "Step-by-step"}
_DASH = '<span class="muted">—</span>'


# -------------------------------------------------------------------- nav

def render_nav(views: List[Dict]) -> str:
    dp_links = "".join(
        f'<a href="#{esc(v["code"])}"><span class="badge b-{v["bucket"]}">'
        f"<i></i></span>{esc(v['code'])}</a>"
        for v in views
    )
    return (
        '<nav class="topnav" aria-label="Report"><div class="tn-in">'
        '<a class="tn-brand" href="#top">DQ Report</a>'
        '<a href="#summary">Overview</a>'
        + dp_links +
        '<span class="tn-sp"></span>'
        '<label class="tn-search js-only">'
        '<input type="search" placeholder="Search CDE, dimension, rule…" '
        'aria-label="Search rules, CDEs and dimensions">'
        '<span class="tn-hits muted"></span></label>'
        '<button type="button" class="tb js-only" data-expand="1">Expand all</button>'
        '<button type="button" class="tb js-only" data-expand="0">Collapse all</button>'
        '<button type="button" class="tb js-only" onclick="window.print()">'
        "Print / PDF</button></div></nav>"
    )


# ----------------------------------------------------------------- header

def _meta_domain(ctx: ReportContext) -> str:
    if not ctx.domain_code and not ctx.domain_name:
        return _DASH
    name = esc(ctx.domain_name) + " " if ctx.domain_name else ""
    return f"{name}<code>{esc(ctx.domain_code or '—')}</code>"


def _meta_scope(ctx: ReportContext) -> str:
    if ctx.data_scope == "sample":
        cap = (f" (max {fmt_int(ctx.sample_rows_cap)} rows per table)"
               if ctx.sample_rows_cap else "")
        return esc(f"Sample{cap}")
    if ctx.data_scope == "full":
        return "Full dataset"
    return _DASH


def render_header(ctx: ReportContext) -> str:
    dp_codes = "".join(f"<code>{esc(c)}</code> " for c in ctx.dp_codes)
    projects = ("".join(f"<code>{esc(p)}</code> " for p in ctx.project_filter)
                or '<span class="muted">none</span>')
    mode = esc(_MODE_LABELS.get(ctx.mode or "", ctx.mode)) if ctx.mode \
        else _DASH
    fields = [
        ("Domain", _meta_domain(ctx)),
        ("Data Products",
         f'{dp_codes}<span class="muted">({len(ctx.dp_codes)})</span>'),
        ("Generated (UTC)", esc(ctx.generated_at) if ctx.generated_at
         else _DASH),
        ("Generated by", esc(ctx.generated_by) if ctx.generated_by
         else _DASH),
        ("Execution mode", mode),
        ("Data scope", _meta_scope(ctx)),
        ("Project filter", projects),
        ("Thresholds",
         f"Green ≥ {ctx.threshold_green:g} · Yellow ≥ {ctx.threshold_yellow:g}"),
        ("Saved project", esc(ctx.saved_project) if ctx.saved_project
         else _DASH),
        ("Run identifier", f"<code>{esc(ctx.run_id)}</code>" if ctx.run_id
         else _DASH),
    ]
    meta = "".join(
        f"<div><dt>{esc(label)}</dt><dd>{value}</dd></div>"
        for label, value in fields
    )
    return (
        '<header class="rh" id="top"><div class="rh-brand">'
        '<span class="rh-kicker">Data Quality Scorecard</span>'
        "<h1>Data Quality Scorecard Report</h1>"
        '<p class="rh-lead">Self-contained snapshot of one scorecard run: '
        "scores, rules, failing rows, history and the exact configuration "
        "behind every number. No application access needed.</p></div>\n"
        f'<dl class="meta">{meta}</dl></header>'
    )


# ---------------------------------------------------------------- summary

def _pct(part: int, total: int) -> float:
    return part / max(total, 1) * 100.0


def _summary_row(view: Dict) -> str:
    result = view["result"]
    code = view["code"]
    drop = view["history"]["drop"]
    if drop is None:
        delta_cell = '<td class="num"><span class="muted">—</span></td>'
        config_cell = '<td><span class="muted">—</span></td>'
    else:
        cls = "pos" if drop["delta"] >= 0 else "neg"
        delta_cell = f'<td class="num {cls}">{drop["delta"]:+.1f} pp</td>'
        config_cell = ('<td><span class="pill p-warn">changed</span></td>'
                       if drop["config_changed"]
                       else '<td><span class="muted">same</span></td>')
    total = result.total_rows

    def bucket_cell(count: int) -> str:
        return (f'<td class="num"><b>{fmt_int(count)}</b> '
                f'<span class="muted">{_pct(count, total):.1f}%</span></td>')

    return (
        f'<tr><td><a href="#{esc(code)}"><b>{esc(view["name"])}</b></a></td>'
        f"<td><code>{esc(code)}</code></td>"
        f'<td class="num big">{result.overall_score:.1f}</td>'
        f'<td class="c-bar">'
        f'{score_bar(result.overall_score, result.threshold_green, result.threshold_yellow)}'
        "</td>"
        f"<td>{tables.badge(view['bucket'])}</td>"
        f'<td class="num">{fmt_int(total)}</td>'
        + bucket_cell(result.rows_green)
        + bucket_cell(result.rows_yellow)
        + bucket_cell(result.rows_red)
        + delta_cell + config_cell + "</tr>"
    )


def _needs_attention(views: List[Dict], ctx: ReportContext) -> str:
    items: List[str] = []
    for v in views:
        if v["bucket"] != "green":
            r = v["result"]
            items.append(
                f"<li>{tables.badge(v['bucket'])} "
                f'<a href="#{esc(v["code"])}"><b>{esc(v["code"])}</b></a> '
                f"scores <b>{r.overall_score:.1f}</b> - "
                f"{fmt_int(r.rows_red)} rows "
                f"({_pct(r.rows_red, r.total_rows):.1f}%) are Red.</li>"
            )
    for v in views:
        drop = v["history"]["drop"]
        if drop is not None and drop["delta"] <= -ctx.drop_alert_pp:
            config = (" - <b>configuration also changed</b>"
                      if drop["config_changed"] else "")
            items.append(
                '<li><span class="pill p-err">drop</span> '
                f'<a href="#{esc(v["code"])}-history"><b>{esc(v["code"])}</b></a> '
                f"fell <b>{abs(drop['delta']):.1f} pp</b> since the previous "
                f"run{config}.</li>"
            )
    for v in views:
        for r in v["not_run"]:
            anchor = "custom" if r["kind"] == "custom" else "std"
            items.append(
                f'<li><span class="pill p-warn">{esc(r["status"])}</span> '
                f'<a href="#{esc(v["code"])}-{anchor}"><b>{esc(v["code"])}</b> '
                f'· <code>{esc(r["rule_id"])}</code></a> - '
                f"{esc(r['reason'] or '')}</li>"
            )
    if not items:
        items.append('<li class="muted">Nothing needs attention - every '
                     "Data Product is Green and every rule ran.</li>")
    return "".join(items)


def _lowest_cdes(views: List[Dict]) -> str:
    flat = [
        (item, v) for v in views for item in v["cde_items"]
        if item["bucket"] != "green"
    ]
    flat.sort(key=lambda pair: pair[0]["score"])
    items = [
        f'<li><span class="num w">{item["score"]:.1f}</span> '
        f"{tables.badge(item['bucket'])} "
        f'<a href="#{esc(v["code"])}-cdes"><code>{esc(v["code"])}</code> '
        f"{esc(item['name'])}</a></li>"
        for item, v in flat[:5]
    ]
    if not items:
        items.append('<li class="muted">Every CDE is Green.</li>')
    return "".join(items)


def _lowest_rules(views: List[Dict]) -> str:
    flat = []
    for v in views:
        for r in v["std_rules"] + v["custom_rules"]:
            if r["status"] != STATUS_EVALUATED:
                continue
            label = (f"{r['cde']} · {r['dimension']}" if r["kind"] == "std"
                     else f"{r['rule_id']} · {r['name']}")
            anchor = "std" if r["kind"] == "std" else "custom"
            flat.append((r["pass_rate"], label, anchor, r["weight"], v))
    flat.sort(key=lambda t: t[0])
    items = [
        f'<li><span class="num w">{rate:.1f}%</span> '
        f'<a href="#{esc(v["code"])}-{anchor}"><code>{esc(v["code"])}</code> '
        f'{esc(label)}</a> <span class="muted">w={weight:.1f}%</span></li>'
        for rate, label, anchor, weight, v in flat[:5]
    ]
    if not items:
        items.append('<li class="muted">No evaluated rules.</li>')
    return "".join(items)


def render_summary(views: List[Dict], ctx: ReportContext) -> str:
    rows = "".join(_summary_row(v) for v in views)
    return (
        '<section class="summary" id="summary" '
        'data-screen-label="Executive summary">\n'
        "<h2>Executive summary</h2>\n"
        '<div class="tw"><table class="exec"><thead><tr><th>Data Product</th>'
        '<th>Code</th><th class="num">Score</th><th></th><th>Status</th>'
        '<th class="num">Rows</th>'
        '<th class="num"><i class="dot d-green"></i>Green</th>'
        '<th class="num"><i class="dot d-yellow"></i>Yellow</th>'
        '<th class="num"><i class="dot d-red"></i>Red</th>'
        '<th class="num">Δ vs previous</th><th>Config</th></tr></thead>'
        f"<tbody>{rows}</tbody></table></div>\n"
        '<div class="attn">\n'
        f'<div><h4>Needs attention</h4><ul class="plain">'
        f"{_needs_attention(views, ctx)}</ul></div>\n"
        f'<div><h4>Lowest-scoring CDEs</h4><ul class="plain">'
        f"{_lowest_cdes(views)}</ul></div>\n"
        f'<div><h4>Lowest pass-rate rules</h4><ul class="plain">'
        f"{_lowest_rules(views)}</ul></div>\n"
        "</div></section>"
    )


# ------------------------------------------------------------- DP section

def _dp_callouts(view: Dict, ctx: ReportContext) -> str:
    parts = []
    drop = view["history"]["drop"]
    code = view["code"]
    if drop is not None and drop["delta"] <= -ctx.drop_alert_pp:
        config = (
            " <b>The configuration also changed between these runs</b> - "
            f'review <a href="#{esc(code)}-changes">What changed</a> before '
            "attributing the drop to the data."
            if drop["config_changed"] else ""
        )
        parts.append(
            f'<div class="callout err"><b>Score dropped '
            f"{abs(drop['delta']):.1f} pp</b> vs the previous run: "
            f"{drop['prev_score']:.1f} → {drop['curr_score']:.1f} "
            f"(previous run {esc(drop['prev_ts'])} by "
            f"{esc(drop['prev_username'])}).{config}</div>"
        )
    if view["not_run"]:
        links = " · ".join(
            f'<a href="#{esc(code)}-{"custom" if r["kind"] == "custom" else "std"}">'
            f'<code>{esc(r["rule_id"])}</code></a> - {esc(r["status"])}'
            for r in view["not_run"]
        )
        parts.append(
            f'<div class="callout warn"><b>{len(view["not_run"])} rule(s) '
            "could not be run</b> and were excluded from the score (weights "
            f"redistributed): {links}. Reasons are in the rule tables.</div>"
        )
    return "".join(parts)


def _sources_card(view: Dict) -> str:
    result = view["result"]
    weights = result.source_weights or {}
    if not weights:
        return ('<div class="ov-src"><h4>Sources</h4>'
                '<p class="muted small">No source breakdown for this run.'
                "</p></div>")
    scores = {"standard": result.standard_score, "custom": result.custom_score}
    seg_cls = {"standard": "s-std", "custom": "s-cus"}
    label = {"standard": "Standard DQRs", "custom": "Custom DQRs"}
    rows, segs = [], []
    for source, weight in weights.items():
        score = scores.get(source)
        value = f"{score:.1f}" if score is not None else "—"
        rows.append(
            f'<div class="src-row"><span class="src-lbl">'
            f"{esc(label.get(source, SOURCE_LABELS.get(source, source)))}</span>"
            f'<span class="num v">{value}</span>'
            f'<span class="muted">weight {weight:.0f}%</span></div>'
        )
        segs.append(f'<span class="{seg_cls.get(source, "s-std")}" '
                    f'style="width:{weight:.0f}%"></span>')
    if all(scores.get(s) is not None for s in weights) and len(weights) > 1:
        formula = " + ".join(
            f"{w:.0f}% × {scores[s]:.1f}" for s, w in weights.items()
        )
        explain = (
            f'<p class="muted small">Overall = {formula} = '
            f"<b>{result.overall_score:.1f}</b>. Each source score is the "
            "mean row score of its own rules; the overall combines them "
            "with the source weights chosen in Step 4.</p>"
        )
    else:
        only = next(iter(weights))
        explain = (
            '<p class="muted small">Overall = the mean row score of the '
            f"{esc(label.get(only, only))} - the only source selected in "
            "Step 4.</p>"
        )
    return ('<div class="ov-src"><h4>Sources</h4>' + "".join(rows)
            + f'<div class="src-bar" aria-hidden="true">{"".join(segs)}</div>'
            + explain + "</div>")


def _overview_grid(view: Dict) -> str:
    result = view["result"]
    g, y = result.threshold_green, result.threshold_yellow
    total = result.total_rows
    pg, py, pr = (_pct(result.rows_green, total), _pct(result.rows_yellow, total),
                  _pct(result.rows_red, total))
    kpis = (
        '<div class="kpis"><div class="kpi"><span class="k">Total rows</span>'
        f'<span class="v">{fmt_int(total)}</span></div>'
        '<div class="kpi"><span class="k"><i class="dot d-green"></i>Green</span>'
        f'<span class="v">{fmt_int(result.rows_green)}</span>'
        f'<span class="s">{pg:.1f}%</span></div>'
        '<div class="kpi"><span class="k"><i class="dot d-yellow"></i>Yellow</span>'
        f'<span class="v">{fmt_int(result.rows_yellow)}</span>'
        f'<span class="s">{py:.1f}%</span></div>'
        '<div class="kpi"><span class="k"><i class="dot d-red"></i>Red</span>'
        f'<span class="v">{fmt_int(result.rows_red)}</span>'
        f'<span class="s">{pr:.1f}%</span></div></div>'
    )
    dist = (
        '<table class="dist"><tbody>'
        f'<tr><td><i class="dot d-green"></i>Green</td>'
        f'<td class="num">{fmt_int(result.rows_green)}</td>'
        f'<td class="num">{pg:.1f}%</td>'
        f'<td class="muted">row score ≥ {g:g}</td></tr>'
        f'<tr><td><i class="dot d-yellow"></i>Yellow</td>'
        f'<td class="num">{fmt_int(result.rows_yellow)}</td>'
        f'<td class="num">{py:.1f}%</td>'
        f'<td class="muted">{y:g} ≤ row score &lt; {g:g}</td></tr>'
        f'<tr><td><i class="dot d-red"></i>Red</td>'
        f'<td class="num">{fmt_int(result.rows_red)}</td>'
        f'<td class="num">{pr:.1f}%</td>'
        f'<td class="muted">row score &lt; {y:g}</td></tr>'
        "</tbody></table>"
    )
    return (
        '<div class="ov-grid">\n'
        f'<div class="ov-score">{gauge_svg(result.overall_score, g, y)}'
        f'<div class="ov-th muted small">Green ≥ {g:g} · Yellow ≥ {y:g} · '
        f"Red &lt; {y:g}</div></div>\n"
        f'<div class="ov-dist">{kpis}{stacked_bar(pg, py, pr)}{dist}</div>\n'
        f"{_sources_card(view)}\n</div>"
    )


def _history_section(view: Dict, ctx: ReportContext) -> str:
    code = view["code"]
    hist = view["history"]
    runs = hist["runs"]
    n = len(runs)
    parts = [
        f'<h3 id="{esc(code)}-history">History '
        f'<span class="h-sub">{n} run(s) recorded</span></h3>'
    ]
    if not runs:
        parts.append(
            '<p class="note">No persisted runs yet - history builds up '
            "automatically every time this scorecard is computed and "
            "survives Restart.</p>"
        )
        return "".join(parts)
    result = view["result"]
    if n >= 2:
        parts.append(
            '<div class="trend-wrap">'
            + trend_svg(runs, result.threshold_green, result.threshold_yellow)
            + "</div>"
            '<p class="muted small">◆ = configuration changed vs the '
            "previous run. Bands show the Green / Yellow / Red thresholds. "
            f"Drop alert threshold: {ctx.drop_alert_pp:g} pp.</p>"
        )
    else:
        parts.append(
            '<p class="note">One run recorded so far - the trend chart '
            "appears from the second run.</p>"
        )
    parts.append("<h5>Run log</h5>" + tables.run_log_table(runs))

    drift = hist["drift"]
    if drift is not None:
        psi = "—" if drift["psi"] is None else f"{drift['psi']:.3f}"
        delta_cls = "pos" if drift["score_delta"] >= 0 else "neg"
        parts.append(
            f'<h3 id="{esc(code)}-changes">What changed vs the previous run</h3>'
            f'<p class="muted small">Comparing {esc(drift["prev"]["ts"])} '
            f"({esc(drift['prev']['user'])}) with {esc(drift['curr']['ts'])} "
            f"({esc(drift['curr']['user'])}). Same drift computation as the "
            "dashboard History tab (|Δ| ≥ 5 pp flags).</p>"
        )
        if drift["config_changed"]:
            parts.append(
                '<div class="callout warn"><b>Configuration changed between '
                "these runs</b> "
                f"(<code>{esc(drift['prev']['config_hash'][:8])}</code> → "
                f"<code>{esc(drift['curr']['config_hash'][:8])}</code>). "
                "Part of the score movement may come from rule / weight "
                "changes rather than from the data. The exact configuration "
                "used for the current score is in "
                f'<a href="#{esc(code)}-config">Configuration used for this '
                "run</a>.</div>"
            )
        parts.append(
            '<div class="kpis"><div class="kpi"><span class="k">Score Δ</span>'
            f'<span class="v {delta_cls}">{drift["score_delta"]:+.2f}</span></div>'
            '<div class="kpi"><span class="k">PSI (row-score distribution)</span>'
            f'<span class="v">{psi}</span></div>'
            '<div class="kpi"><span class="k">Flagged changes (|Δ| ≥ 5 pp)</span>'
            f'<span class="v">{drift["flagged_total"]}</span></div></div>'
        )
        if drift["flagged_total"]:
            parts.append(tables.drift_tables(drift))
        else:
            parts.append('<p class="note ok">Nothing moved ≥ 5 pp between '
                         "the last two runs.</p>")
    return "".join(parts)


def render_dp(view: Dict, ctx: ReportContext) -> str:
    code = view["code"]
    result = view["result"]
    accent = _SYSTEM_ACCENTS.get(code, _DEFAULT_ACCENT)
    subnav = "".join(
        f'<a href="#{esc(code)}-{anchor}">{label}</a>'
        for anchor, label in (
            ("overview", "Overview"), ("cdes", "CDEs"),
            ("dims", "Dimensions"), ("std", "Standard DQRs"),
            ("custom", "Custom DQRs"), ("rows", "Worst rows"),
            ("history", "History"), ("config", "Configuration"),
        )
    )
    source_tables = " ".join(
        f"<code>{esc(t)}</code>" for t in view["source_tables"]
    ) or '<span class="muted">—</span>'

    n_std = len(view["std_rules"])
    n_std_skip = sum(1 for r in view["std_rules"]
                     if r["status"] != STATUS_EVALUATED)
    n_cus = len(view["custom_rules"])
    n_cus_skip = sum(1 for r in view["custom_rules"]
                     if r["status"] != STATUS_EVALUATED)

    cde_block = (
        tables.toolbar_sort_only() + tables.group_list(view, view["cde_items"], "cde")
        if view["cde_items"] else
        '<p class="note">No CDEs selected for this Data Product.</p>'
    )
    dim_block = (
        tables.toolbar_sort_only() + tables.group_list(view, view["dim_items"], "dim")
        if view["dim_items"] else
        '<p class="note">No dimensions scored for this Data Product.</p>'
    )
    std_block = (
        tables.toolbar_rules(custom=False) + tables.std_rules_list(view)
        if view["std_rules"] else
        '<p class="note">No Standard DQRs defined for this Data Product.</p>'
    )
    cus_block = (
        tables.toolbar_rules(custom=True) + tables.custom_rules_list(view)
        if view["custom_rules"] else
        '<p class="note">No custom rules selected for this Data Product.</p>'
    )

    n_shown = min(ctx.caps.worst_rows, len(view["store_rows"]))
    worst_note = (
        f'<p class="note">Showing the {fmt_int(n_shown)} lowest-scoring rows '
        f"of {fmt_int(result.total_rows)}. The CSV export "
        f"(<code>{esc(code)}_row_scores.csv</code>) carries every row.</p>"
        if n_shown else ""
    )

    return (
        f'<section class="dp" id="{esc(code)}" '
        f'data-screen-label="{esc(code)}" style="--accent:{accent}">\n'
        f'<header class="dp-head" id="{esc(code)}-overview">'
        f'<div class="dp-title"><span class="code">{esc(code)}</span>'
        f"<h2>{esc(view['name'])}</h2>{tables.badge(view['bucket'])}</div>"
        f'<nav class="subnav" aria-label="{esc(code)} sections">{subnav}</nav>'
        "</header>\n"
        f'<div class="dp-meta muted small">{fmt_int(view["n_rows"])} rows · '
        f"{fmt_int(view['n_cols'])} columns · source tables: {source_tables}"
        "</div>\n"
        + _dp_callouts(view, ctx)
        + _overview_grid(view)
        + f'\n<h3 id="{esc(code)}-cdes">By CDE <span class="h-sub">'
        f"{len(view['cde_items'])} critical data elements</span></h3>\n"
        '<p class="muted small">Each score is the unweighted mean of the '
        "pass rates of every evaluated rule tied to that CDE - Standard "
        "rules via their CDE, Custom rules via the columns they read. "
        "Step 5 weights do not affect this view. Expand a CDE to see its "
        "rules and failing rows.</p>\n"
        + cde_block
        + f'\n<h3 id="{esc(code)}-dims">By Dimension <span class="h-sub">'
        f"{len(view['dim_items'])} dimensions</span></h3>\n"
        '<p class="muted small">Unweighted mean of the pass rates of every '
        "evaluated rule of that dimension (Custom rules count via their "
        "type). Dimensions whose only rule was not computed do not appear."
        "</p>\n"
        + dim_block
        + f'\n<h3 id="{esc(code)}-std">Standard DQRs <span class="h-sub">'
        f"{n_std} rules · {n_std_skip} not computed</span></h3>\n"
        + std_block
        + f'\n<h3 id="{esc(code)}-custom">Custom DQRs <span class="h-sub">'
        f"{n_cus} rules · {n_cus_skip} not evaluated</span></h3>\n"
        + cus_block
        + f'\n<h3 id="{esc(code)}-rows">Worst rows <span class="h-sub">'
        f"{fmt_int(n_shown)} lowest-scoring of {fmt_int(result.total_rows)}"
        "</span></h3>\n"
        '<p class="muted small">Row score, status, every Data Product '
        "field, the reference-dataset fields the Custom rules joined "
        "(suffixed with the dataset), then one column per evaluated rule: "
        "<b>100</b> = pass, <b>0</b> = fail, weight in the header. Rules "
        "that were not computed have no column. Click a truncated value to "
        "see it in full.</p>\n"
        + tables.worst_rows_table(view, ctx.caps) + worst_note
        + "\n" + _history_section(view, ctx)
        + "\n" + tables.config_snapshot(view)
        + '\n<p class="totop"><a href="#top">↑ Back to top</a></p>\n</section>'
    )


# ----------------------------------------------------------------- footer

def render_footer(ctx: ReportContext) -> str:
    run = (f" · run <code>{esc(ctx.run_id)}</code>" if ctx.run_id else "")
    who = f" by {esc(ctx.generated_by)}" if ctx.generated_by else ""
    return (
        f'<footer class="foot"><p>Generated {esc(ctx.generated_at)}{who} · '
        f"Data Quality Scorecard{run}. This file is a self-contained "
        "snapshot: it embeds every table, chart and the "
        f"{fmt_int(ctx.caps.row_store)} lowest-scoring rows per Data Product "
        f"(worst-rows table: {fmt_int(ctx.caps.worst_rows)}; drill-downs: "
        f"up to {fmt_int(ctx.caps.drill_rows)} rows each). Totals always "
        "refer to the full dataset; the per-Data-Product CSV export carries "
        "every row. Scores, thresholds and rule semantics are identical to "
        "the Streamlit dashboard for this run.</p></footer>"
    )
