"""Embedded stylesheet for the Data Quality Report.

``REPORT_CSS`` is the design handoff's ``reference/report.css``
embedded verbatim (single source of visual truth): design tokens,
layout, tables, badges, toolbars, print stylesheet. Do not edit the
CSS here - regenerate from the handoff if the design changes.
"""

# The leading newline of the literal is sliced off so the constant
# matches the handoff file byte-for-byte.
REPORT_CSS = """
:root{color-scheme:light;--ink:#1f2937;--ink-2:#334155;--muted:#64748b;--line:#e5e7eb;--line-2:#cbd5e1;--bg:#fff;--bg-2:#f8fafc;--bg-3:#f1f5f9;--brand:#3b4d8f;--green:#16a34a;--yellow:#eab308;--red:#dc2626;--green-bg:rgba(22,163,74,.12);--yellow-bg:rgba(234,179,8,.2);--red-bg:rgba(220,38,38,.12);--green-ink:#166534;--yellow-ink:#854d0e;--red-ink:#991b1b;--mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;--sans:"Segoe UI",-apple-system,BlinkMacSystemFont,Helvetica,Arial,sans-serif}
*{box-sizing:border-box}html{scroll-padding-top:64px}body{margin:0;font:14px/1.5 var(--sans);color:var(--ink);background:var(--bg-2)}
a{color:var(--brand)}a:hover{color:#1e2a5e}code{font-family:var(--mono);font-size:.86em;background:var(--bg-3);padding:.08em .38em;border-radius:4px;color:var(--ink-2)}
.num{font-variant-numeric:tabular-nums;text-align:right}.muted{color:var(--muted)}.small{font-size:12.5px}.null{color:#9ca3af;font-style:italic}.neg{color:var(--red-ink);font-weight:600}.pos{color:var(--green-ink);font-weight:600}
h1{font-size:26px;margin:.1em 0 .3em;letter-spacing:-.01em}h2{font-size:20px;margin:0}h3{font-size:16px;margin:2.2em 0 .5em;padding-top:1.2em;border-top:1px solid var(--line);display:flex;align-items:baseline;gap:.6em}h4{font-size:12px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);margin:0 0 .5em}h5{font-size:12px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);margin:1.1em 0 .4em}.h-sub{font-size:12.5px;font-weight:400;color:var(--muted)}
.wrap{max-width:1280px;margin:0 auto;padding:0 24px 64px}
.topnav{position:sticky;top:0;z-index:20;background:rgba(255,255,255,.96);backdrop-filter:blur(6px);border-bottom:1px solid var(--line)}.tn-in{max-width:1280px;margin:0 auto;padding:0 24px;display:flex;align-items:center;gap:4px;height:48px;overflow-x:auto}.topnav a{color:var(--ink-2);text-decoration:none;padding:6px 10px;border-radius:6px;font-weight:500;white-space:nowrap;display:inline-flex;align-items:center;gap:6px}.topnav a:hover{background:var(--bg-3)}.tn-brand{font-weight:700;color:var(--brand)!important;margin-right:8px}.tn-sp{flex:1}.tn-search{display:flex;align-items:center;gap:6px}.tn-search input{font:inherit;font-size:13px;padding:5px 9px;border:1px solid var(--line-2);border-radius:6px;width:230px;background:#fff}.tn-search input:focus{outline:2px solid var(--brand);outline-offset:1px}.tn-hits{font-size:12px;min-width:3em}
.rh{padding:36px 0 20px;display:grid;grid-template-columns:1.1fr 1fr;gap:32px;align-items:start}.rh-kicker{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:var(--brand);font-weight:700}.rh-lead{color:var(--muted);margin:.4em 0 0;max-width:52ch;text-wrap:pretty}
.meta{margin:0;display:grid;grid-template-columns:1fr 1fr;gap:10px 20px;background:#fff;border:1px solid var(--line);border-radius:10px;padding:16px 18px}.meta div{display:flex;flex-direction:column;gap:2px}.meta dt{font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted)}.meta dd{margin:0;font-size:13px}
section.summary,section.dp{background:#fff;border:1px solid var(--line);border-radius:12px;padding:24px 28px;margin:16px 0}section.dp{border-top:4px solid var(--accent,var(--brand))}
table{border-collapse:collapse;width:100%;font-size:13px}th,td{padding:6px 10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{font-size:11.5px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted);background:var(--bg-2);position:sticky;top:0;z-index:1;white-space:nowrap}th.num,td.num{text-align:right}tbody tr:nth-child(even){background:rgba(15,23,42,.015)}tbody tr:hover{background:rgba(59,77,143,.05)}
table.exec td{padding:10px}table.exec td.big{font-size:20px;font-weight:700}table.exec .c-bar{width:140px}
table.compact{font-size:12.5px}table.compact th,table.compact td{padding:4px 8px}
.tw{overflow:auto;border:1px solid var(--line);border-radius:8px;max-height:520px;background:#fff}.tw table{margin:0}.tw th{white-space:nowrap}
table.rows{font-size:12px;width:max-content;min-width:100%}table.rows td,table.rows th{padding:4px 8px;white-space:nowrap}table.rows th.th-rule{background:#eef2ff;color:#3730a3}table.rows th.th-ref{background:#f0f9ff;color:#075985}table.rows th.hl{outline:2px solid var(--brand);outline-offset:-2px}table.rows td.flag{font-weight:600}table.rows td.f-fail{background:var(--red-bg);color:var(--red-ink)}table.rows td.f-pass{color:var(--green-ink)}table.rows th .tv{max-width:170px}
.tv{display:inline-block;max-width:220px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;vertical-align:bottom;cursor:default}.tv.open{max-width:none;white-space:normal;word-break:break-all}
.badge{display:inline-flex;align-items:center;gap:6px;padding:2px 9px;border-radius:999px;font-size:12px;font-weight:600;white-space:nowrap}.badge i{width:8px;height:8px;border-radius:50%;display:inline-block}.b-green{background:var(--green-bg);color:var(--green-ink)}.b-green i{background:var(--green)}.b-yellow{background:var(--yellow-bg);color:var(--yellow-ink)}.b-yellow i{background:var(--yellow)}.b-red{background:var(--red-bg);color:var(--red-ink)}.b-red i{background:var(--red)}
.pill{display:inline-block;padding:1px 7px;border-radius:5px;font-size:11.5px;font-weight:600;white-space:nowrap}.p-ok{background:var(--green-bg);color:var(--green-ink)}.p-warn{background:var(--yellow-bg);color:var(--yellow-ink)}.p-err{background:var(--red-bg);color:var(--red-ink)}
.dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:6px;vertical-align:middle}.d-green{background:var(--green)}.d-yellow{background:var(--yellow)}.d-red{background:var(--red)}
.bar{display:block;height:10px;background:var(--bg-3);border-radius:5px;overflow:hidden;min-width:80px}.bar-fill{display:block;height:100%}.f-green{background:var(--green)}.f-yellow{background:var(--yellow)}.f-red{background:var(--red)}
.callout{border:1px solid;border-radius:8px;padding:10px 14px;margin:12px 0;font-size:13px}.callout.err{background:rgba(220,38,38,.06);border-color:rgba(220,38,38,.3);color:#7f1d1d}.callout.warn{background:rgba(234,179,8,.08);border-color:rgba(234,179,8,.45);color:#713f12}.callout a{color:inherit}
.note{font-size:12.5px;color:var(--muted);margin:.6em 0}.note.ok{color:var(--green-ink)}.note.info{color:#075985}
.dp-head{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}.dp-title{display:flex;align-items:center;gap:12px}.dp-title .code{font:700 12px var(--mono);letter-spacing:.06em;background:var(--accent,var(--brand));color:#fff;padding:3px 8px;border-radius:6px}.subnav{display:flex;gap:2px;flex-wrap:wrap}.subnav a{text-decoration:none;font-size:12.5px;padding:4px 9px;border-radius:6px;color:var(--ink-2)}.subnav a:hover{background:var(--bg-3)}.dp-meta{margin:6px 0 14px}
.ov-grid{display:grid;grid-template-columns:200px 1fr 300px;gap:28px;align-items:start;margin-top:8px}.ov-score{text-align:center}.gauge{width:100%;max-width:200px}.gauge .fill{stroke:currentColor}.g-green{color:var(--green)}.g-yellow{color:var(--yellow)}.g-red{color:var(--red)}.g-num{font:700 26px var(--sans);fill:var(--ink)}.g-sub{font:11px var(--sans);fill:var(--muted)}
.kpis{display:flex;gap:28px;flex-wrap:wrap;margin:6px 0 14px}.kpi{display:flex;flex-direction:column}.kpi .k{font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted)}.kpi .v{font-size:22px;font-weight:700;line-height:1.2;font-variant-numeric:tabular-nums}.kpi .s{font-size:12px;color:var(--muted)}
.stack{display:flex;height:18px;border-radius:5px;overflow:hidden;background:var(--bg-3)}.stack .seg{display:block;height:100%}table.dist{width:auto;margin-top:8px;font-size:13px}table.dist td{padding:3px 12px 3px 0;border:0}
.ov-src{background:var(--bg-2);border:1px solid var(--line);border-radius:10px;padding:14px 16px}.src-row{display:flex;align-items:baseline;gap:10px;padding:4px 0}.src-lbl{flex:1;font-weight:600}.src-row .v{font-size:20px;font-weight:700}.src-bar{display:flex;height:8px;border-radius:4px;overflow:hidden;margin:8px 0 6px}.s-std{background:#6366f1}.s-cus{background:#f59e0b}.ov-src p{margin:.4em 0 0}
.toolbar{display:flex;align-items:center;gap:6px;flex-wrap:wrap;margin:0 0 8px}.tb-group{display:inline-flex;gap:0;border:1px solid var(--line-2);border-radius:6px;overflow:hidden}.tb-group .tb{border:0;border-radius:0;border-right:1px solid var(--line)}.tb-group .tb:last-child{border-right:0}.tb{font:inherit;font-size:12.5px;padding:4px 10px;border:1px solid var(--line-2);border-radius:6px;background:#fff;color:var(--ink-2);cursor:pointer}.tb:hover{background:var(--bg-3)}.tb.on{background:var(--brand);color:#fff;border-color:var(--brand)}.tb.chk{display:inline-flex;align-items:center;gap:6px;cursor:pointer}.tb:focus-visible,summary:focus-visible,a:focus-visible,input:focus-visible{outline:2px solid var(--brand);outline-offset:2px}.tb-count{font-size:12px;margin-left:auto}
.gl{border:1px solid var(--line);border-radius:8px;overflow:hidden;background:#fff}.gl-grid{display:grid;gap:12px;align-items:center;padding:7px 12px}.gl-head{font-size:11.5px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted);background:var(--bg-2);border-bottom:1px solid var(--line)}
.cde-grid,.dim-grid{grid-template-columns:minmax(160px,1.4fr) minmax(120px,2fr) 60px 100px 60px 130px}.std-grid{grid-template-columns:minmax(150px,1.3fr) 120px 70px 110px minmax(100px,1.2fr) 70px 70px 100px}.cus-grid{grid-template-columns:52px minmax(200px,2fr) minmax(120px,1fr) 80px 110px 70px minmax(90px,1fr) 70px 100px}
.gl-row{border-bottom:1px solid var(--line)}.gl-row:last-child{border-bottom:0}.gl-row>summary{list-style:none;cursor:pointer;font-size:13px}.gl-row>summary::-webkit-details-marker{display:none}.gl-row>summary:hover{background:rgba(59,77,143,.05)}.gl-row[open]>summary{background:var(--bg-2);border-bottom:1px solid var(--line)}.gl-row>summary .c-name{font-weight:600;display:flex;align-items:center;gap:8px}.gl-row>summary .c-name::before{content:"▸";color:var(--muted);font-size:11px;transition:transform .15s}.gl-row[open]>summary .c-name::before{transform:rotate(90deg)}.gl-row.hidden{display:none}
.gl-body{padding:12px 16px 16px 30px;background:#fff;font-size:13px}.gl-body .desc{margin:.3em 0;max-width:90ch;text-wrap:pretty}.two{display:grid;grid-template-columns:1fr 1fr;gap:24px}.kv{display:grid;grid-template-columns:max-content 1fr;gap:3px 14px;margin:.3em 0;font-size:12.5px}.kv dt{color:var(--muted)}.kv dd{margin:0}
.rule-list{margin:.2em 0;padding-left:1.1em;font-size:12.5px}.rule-list li{margin:2px 0}.chips{display:flex;flex-wrap:wrap;gap:6px;margin:.3em 0}
.drill{margin-top:10px;border-top:1px dashed var(--line);padding-top:8px}.drill .tw{max-height:360px}.drill .cap{font-size:12px;color:var(--muted);margin:.4em 0}
.trend-wrap{max-width:720px}.trend{width:100%;height:auto}.t-val{font:600 11px var(--sans);fill:var(--ink)}.t-ax{font:10.5px var(--sans);fill:var(--muted)}
details.cfg{margin-top:2.2em;border-top:1px solid var(--line);padding-top:1.2em}details.cfg>summary{cursor:pointer;list-style:none;display:flex;align-items:center;gap:8px}details.cfg>summary::-webkit-details-marker{display:none}details.cfg>summary h3{margin:0;padding:0;border:0}details.cfg>summary::before{content:"▸";color:var(--muted)}details.cfg[open]>summary::before{content:"▾"}.cfg-body{padding-top:8px}
.attn{display:grid;grid-template-columns:1.3fr 1fr 1fr;gap:24px;margin-top:20px}.plain{list-style:none;padding:0;margin:0;font-size:13px}.plain li{padding:6px 0;border-bottom:1px solid var(--line);display:block;line-height:1.55}.plain li>*{vertical-align:middle}.plain li .badge,.plain li .pill{margin-right:4px}.plain li:last-child{border:0}.plain .w{min-width:3.6em;font-weight:700}
.totop{text-align:right;font-size:12px;margin:24px 0 0}.foot{color:var(--muted);font-size:12px;padding:20px 4px;text-wrap:pretty}
.js-only{display:none}.js .js-only{display:inline-flex}.js .toolbar.js-only{display:flex}.js span.js-only{display:inline}
@media (max-width:1000px){.rh,.ov-grid,.attn,.two{grid-template-columns:1fr}.meta{grid-template-columns:1fr 1fr}.tn-search input{width:150px}.gl-grid{gap:8px}.cde-grid,.dim-grid{grid-template-columns:minmax(120px,1.4fr) 1fr 50px 90px}.cde-grid>:nth-child(n+5),.dim-grid>:nth-child(n+5){display:none}.std-grid{grid-template-columns:1.3fr 1fr 60px 100px 70px}.std-grid>:nth-child(5),.std-grid>:nth-child(7),.std-grid>:nth-child(8){display:none}.cus-grid{grid-template-columns:48px 2fr 100px 70px}.cus-grid>:nth-child(3),.cus-grid>:nth-child(4),.cus-grid>:nth-child(6),.cus-grid>:nth-child(7),.cus-grid>:nth-child(9){display:none}}
@media (max-width:640px){.wrap{padding:0 12px 40px}section.summary,section.dp{padding:16px}.meta{grid-template-columns:1fr}.kpis{gap:16px}}
@media print{@page{margin:14mm}body{background:#fff;font-size:11.5px}.topnav,.toolbar,.totop,.js-only,.tn-search{display:none!important}.wrap{max-width:none;padding:0}section.summary,section.dp{border:0;border-radius:0;padding:0;margin:0}section.dp{page-break-before:always;border-top:3px solid var(--accent,var(--brand));padding-top:12px}.tw{max-height:none;overflow:visible;border:0}th{position:static}table.rows{font-size:9px}.tv{max-width:120px}.gl-row,.callout,.kpi,tr{break-inside:avoid}h3{break-after:avoid}*{-webkit-print-color-adjust:exact;print-color-adjust:exact}a{color:inherit;text-decoration:none}.rh{grid-template-columns:1fr 1fr}}
"""[1:]
