"""Custom DQR engine - public entry point.

Standard DQRs (10 dimensions) live in :mod:`src.dqr_engine`. This module
hosts the *data-product-specific* check functions registered in
:mod:`config.custom_dqr_catalog` and a dispatcher
(:func:`evaluate_custom_rules`) that mirrors :func:`src.dqr_engine.evaluate_all`
but works against :class:`src.models.CustomDQRAssignment` selections.

The implementation has been partitioned by rule family into
:mod:`src.custom_dqr`. This module re-exports the public names so external
callers (the catalog, the UI tests, the dispatcher) keep importing from
``src.custom_dqr_engine`` exactly as before. To add a new rule, edit the
appropriate ``src/custom_dqr/_<family>_rules.py`` module and add the
symbol to the matching block below.

Two failure modes are distinguished:

- **Missing required columns**: the rule fails for every row (returns an
  all-False Series), the data is present but incomplete.
- **Missing dependencies** (e.g. a reference dataset): the rule raises
  :class:`CustomRuleNotEvaluated`. The dispatcher records the reason,
  omits the rule from the Boolean results, and surfaces a "not evaluated"
  state in Step 6 so the failure is never silent.

Reusable validators (:func:`validate_completeness_rule`,
:func:`validate_referential_integrity_rule`) are re-exported for new rule
modules to compose.
"""
from __future__ import annotations

from src.custom_dqr._acce_rules import (
    ACCE_AC1_REFERENCE,
    ACCE_AC1_REQUIRED_COLUMNS,
    ACCE_AC2_JOB_NO_PATTERN,
    ACCE_AC2_REFERENCE,
    ACCE_AC2_REQUIRED_COLUMNS,
    ACCE_AC3_DETECT_UNIFORM_MAPPING_PARAM,
    ACCE_AC3_MATERIALITY_USD,
    ACCE_AC3_MIN_MAPPING_POPULATION,
    ACCE_AC3_PERCENTILE,
    ACCE_AC3_REFERENCE,
    ACCE_AC3_REQUIRED_COLUMNS,
    ACCE_AC3_THRESHOLD_CHOICES,
    ACCE_AC3_THRESHOLD_PARAM,
    ACCE_AC3_UNIFORM_THRESHOLD,
    ACCE_AC4_REQUIRED_COLUMNS,
    ACCE_AC5_REQUIRED_COLUMNS,
    ACCE_AC6_REQUIRED_COLUMNS,
    ACCE_AC7_EXTREME_IQR_MULTIPLIER,
    ACCE_AC7_MILD_IQR_MULTIPLIER,
    ACCE_AC7_MIN_POPULATION,
    ACCE_AC7_REQUIRED_COLUMNS,
    ACCE_AC7_SEGMENT_BY_PROJECT_TYPE_PARAM,
    ACCE_AC7_SEGMENT_REFERENCE,
    ACCE_AC7_SEGMENT_REQUIRED_COLUMNS,
    ACCE_AC7_THRESHOLD_CHOICES,
    ACCE_AC7_THRESHOLD_PARAM,
    ACCE_AC8_EXTREME_IQR_MULTIPLIER,
    ACCE_AC8_MILD_IQR_MULTIPLIER,
    ACCE_AC8_MIN_POPULATION,
    ACCE_AC8_REQUIRED_COLUMNS,
    ACCE_AC8_SEGMENT_BY_PROJECT_TYPE_PARAM,
    ACCE_AC8_SEGMENT_REFERENCE,
    ACCE_AC8_SEGMENT_REQUIRED_COLUMNS,
    ACCE_AC8_THRESHOLD_CHOICES,
    ACCE_AC8_THRESHOLD_PARAM,
    ACCEAC3Params,
    ACCEAC7Params,
    ACCEAC8Params,
    _classify_ac4_quantity_acce,
    _classify_ac4_scope_acce,
    _classify_ac8_category_acce,
    check_acce_ac1,
    check_acce_ac2,
    check_acce_ac3,
    check_acce_ac4,
    check_acce_ac5,
    check_acce_ac6,
    check_acce_ac7,
    check_acce_ac8,
)
from src.custom_dqr._adr_rules import (
    ADR_A1_REFERENCE,
    ADR_A1_REQUIRED_COLUMNS,
    ADR_A2_DATE_PATTERN,
    ADR_A2_REFERENCE,
    ADR_A2_REQUIRED_COLUMNS,
    ADR_A3_DETECT_UNIFORM_MAPPING_PARAM,
    ADR_A3_MATERIALITY_USD,
    ADR_A3_MIN_MAPPING_POPULATION,
    ADR_A3_PERCENTILE,
    ADR_A3_PROJECT_SCOPED_PARAM,
    ADR_A3_PROJECT_SCOPED_REQUIRED_COLUMNS,
    ADR_A3_REFERENCE,
    ADR_A3_REQUIRED_COLUMNS,
    ADR_A3_THRESHOLD_CHOICES,
    ADR_A3_THRESHOLD_PARAM,
    ADR_A4_REQUIRED_COLUMNS,
    ADR_A5_REQUIRED_COLUMNS,
    ADR_A6_REQUIRED_COLUMNS,
    ADR_A7_EXTREME_IQR_MULTIPLIER,
    ADR_A7_MILD_IQR_MULTIPLIER,
    ADR_A7_MIN_POPULATION,
    ADR_A7_REQUIRED_COLUMNS,
    ADR_A7_SEGMENT_BY_PROJECT_TYPE_PARAM,
    ADR_A7_SEGMENT_REFERENCE,
    ADR_A7_SEGMENT_REQUIRED_COLUMNS,
    ADR_A7_THRESHOLD_CHOICES,
    ADR_A7_THRESHOLD_PARAM,
    ADR_A8_EXTREME_IQR_MULTIPLIER,
    ADR_A8_MILD_IQR_MULTIPLIER,
    ADR_A8_MIN_POPULATION,
    ADR_A8_REQUIRED_COLUMNS,
    ADR_A8_SEGMENT_BY_PROJECT_TYPE_PARAM,
    ADR_A8_SEGMENT_REFERENCE,
    ADR_A8_SEGMENT_REQUIRED_COLUMNS,
    ADR_A8_THRESHOLD_CHOICES,
    ADR_A8_THRESHOLD_PARAM,
    ADRA3Params,
    ADRA7Params,
    ADRA8Params,
    _a1_value_valid,
    _classify_a4_quantity,
    _classify_a4_scope,
    _classify_a8_category,
    _resolve_coa_master_lookups,
    check_adr_a1,
    check_adr_a2,
    check_adr_a3,
    check_adr_a4,
    check_adr_a5,
    check_adr_a6,
    check_adr_a7,
    check_adr_a8,
)
from src.custom_dqr._dispatcher import evaluate_custom_rules
from src.custom_dqr._ept_rules import (
    EPT_E1_REQUIRED_COLUMNS,
    EPT_E2_REFERENCE,
    EPT_E2_REQUIRED_COLUMNS,
    EPT_E3_DETECT_UNIFORM_MAPPING_PARAM,
    EPT_E3_MATERIALITY_USD,
    EPT_E3_PERCENTILE,
    EPT_E3_PROJECT_SCOPED_PARAM,
    EPT_E3_PROJECT_SCOPED_REQUIRED_COLUMNS,
    EPT_E3_REQUIRED_COLUMNS,
    EPT_E3_THRESHOLD_CHOICES,
    EPT_E3_THRESHOLD_PARAM,
    EPT_E4_REQUIRED_COLUMNS,
    EPT_E5_FEED_ENGINEERING_PATTERN,
    EPT_E5_REQUIRED_COLUMNS,
    EPT_E6_EXTREME_IQR_MULTIPLIER,
    EPT_E6_MILD_IQR_MULTIPLIER,
    EPT_E6_MIN_POPULATION,
    EPT_E6_REQUIRED_COLUMNS,
    EPT_E6_SEGMENT_BY_PROJECT_TYPE_PARAM,
    EPT_E6_SEGMENT_REFERENCE,
    EPT_E6_THRESHOLD_CHOICES,
    EPT_E6_THRESHOLD_PARAM,
    EPT_E7_REFERENCE,
    EPT_E7_REQUIRED_COLUMNS,
    EPTE3Params,
    EPTE6Params,
    check_ept_e1,
    check_ept_e2,
    check_ept_e3,
    check_ept_e4,
    check_ept_e5,
    check_ept_e6,
    check_ept_e7,
)
from src.custom_dqr._shared import (
    CustomRuleNotEvaluated,
    _check_supports_params,
    _coerce_threshold,
    _is_filled,
    _resolve_planview_segment_map,
)
from src.custom_dqr._sqs_rules import (
    SQS_DQ_INSPECTION_12_COMPLETED_STATUS,
    SQS_DQ_INSPECTION_12_REQUIRED_COLUMNS,
    SQS_DQ_INSPECTION_13_REQUIRED_COLUMNS,
    check_sqs_dq_inspection_12,
    check_sqs_dq_inspection_13,
)
from src.custom_dqr._validators import (
    validate_completeness_rule,
    validate_referential_integrity_rule,
)

__all__ = [
    "CustomRuleNotEvaluated",
    "validate_completeness_rule",
    "validate_referential_integrity_rule",
    "evaluate_custom_rules",
    # TypedDict for assignment.params per parametric rule. ``total=False``
    # so any missing key falls back to the module-level default.
    "EPTE3Params",
    "EPTE6Params",
    "ADRA3Params",
    "ADRA7Params",
    "ADRA8Params",
    "ACCEAC3Params",
    "ACCEAC7Params",
    "ACCEAC8Params",
    # EPT
    "EPT_E1_REQUIRED_COLUMNS",
    "EPT_E2_REFERENCE",
    "EPT_E2_REQUIRED_COLUMNS",
    "EPT_E3_DETECT_UNIFORM_MAPPING_PARAM",
    "EPT_E3_MATERIALITY_USD",
    "EPT_E3_PERCENTILE",
    "EPT_E3_PROJECT_SCOPED_PARAM",
    "EPT_E3_PROJECT_SCOPED_REQUIRED_COLUMNS",
    "EPT_E3_REQUIRED_COLUMNS",
    "EPT_E3_THRESHOLD_CHOICES",
    "EPT_E3_THRESHOLD_PARAM",
    "EPT_E4_REQUIRED_COLUMNS",
    "EPT_E5_FEED_ENGINEERING_PATTERN",
    "EPT_E5_REQUIRED_COLUMNS",
    "EPT_E6_EXTREME_IQR_MULTIPLIER",
    "EPT_E6_MILD_IQR_MULTIPLIER",
    "EPT_E6_MIN_POPULATION",
    "EPT_E6_REQUIRED_COLUMNS",
    "EPT_E6_SEGMENT_BY_PROJECT_TYPE_PARAM",
    "EPT_E6_SEGMENT_REFERENCE",
    "EPT_E6_THRESHOLD_CHOICES",
    "EPT_E6_THRESHOLD_PARAM",
    "EPT_E7_REFERENCE",
    "EPT_E7_REQUIRED_COLUMNS",
    "check_ept_e1",
    "check_ept_e2",
    "check_ept_e3",
    "check_ept_e4",
    "check_ept_e5",
    "check_ept_e6",
    "check_ept_e7",
    # ADR
    "ADR_A1_REFERENCE",
    "ADR_A1_REQUIRED_COLUMNS",
    "ADR_A2_DATE_PATTERN",
    "ADR_A2_REFERENCE",
    "ADR_A2_REQUIRED_COLUMNS",
    "ADR_A3_DETECT_UNIFORM_MAPPING_PARAM",
    "ADR_A3_MATERIALITY_USD",
    "ADR_A3_MIN_MAPPING_POPULATION",
    "ADR_A3_PERCENTILE",
    "ADR_A3_PROJECT_SCOPED_PARAM",
    "ADR_A3_PROJECT_SCOPED_REQUIRED_COLUMNS",
    "ADR_A3_REFERENCE",
    "ADR_A3_REQUIRED_COLUMNS",
    "ADR_A3_THRESHOLD_CHOICES",
    "ADR_A3_THRESHOLD_PARAM",
    "ADR_A4_REQUIRED_COLUMNS",
    "ADR_A5_REQUIRED_COLUMNS",
    "ADR_A6_REQUIRED_COLUMNS",
    "ADR_A7_EXTREME_IQR_MULTIPLIER",
    "ADR_A7_MILD_IQR_MULTIPLIER",
    "ADR_A7_MIN_POPULATION",
    "ADR_A7_REQUIRED_COLUMNS",
    "ADR_A7_SEGMENT_BY_PROJECT_TYPE_PARAM",
    "ADR_A7_SEGMENT_REFERENCE",
    "ADR_A7_SEGMENT_REQUIRED_COLUMNS",
    "ADR_A7_THRESHOLD_CHOICES",
    "ADR_A7_THRESHOLD_PARAM",
    "ADR_A8_EXTREME_IQR_MULTIPLIER",
    "ADR_A8_MILD_IQR_MULTIPLIER",
    "ADR_A8_MIN_POPULATION",
    "ADR_A8_REQUIRED_COLUMNS",
    "ADR_A8_SEGMENT_BY_PROJECT_TYPE_PARAM",
    "ADR_A8_SEGMENT_REFERENCE",
    "ADR_A8_SEGMENT_REQUIRED_COLUMNS",
    "ADR_A8_THRESHOLD_CHOICES",
    "ADR_A8_THRESHOLD_PARAM",
    "check_adr_a1",
    "check_adr_a2",
    "check_adr_a3",
    "check_adr_a4",
    "check_adr_a5",
    "check_adr_a6",
    "check_adr_a7",
    "check_adr_a8",
    # ACCE
    "ACCE_AC1_REFERENCE",
    "ACCE_AC1_REQUIRED_COLUMNS",
    "ACCE_AC2_JOB_NO_PATTERN",
    "ACCE_AC2_REFERENCE",
    "ACCE_AC2_REQUIRED_COLUMNS",
    "ACCE_AC3_DETECT_UNIFORM_MAPPING_PARAM",
    "ACCE_AC3_MATERIALITY_USD",
    "ACCE_AC3_MIN_MAPPING_POPULATION",
    "ACCE_AC3_PERCENTILE",
    "ACCE_AC3_REFERENCE",
    "ACCE_AC3_REQUIRED_COLUMNS",
    "ACCE_AC3_THRESHOLD_CHOICES",
    "ACCE_AC3_THRESHOLD_PARAM",
    "ACCE_AC3_UNIFORM_THRESHOLD",
    "ACCE_AC4_REQUIRED_COLUMNS",
    "ACCE_AC5_REQUIRED_COLUMNS",
    "ACCE_AC6_REQUIRED_COLUMNS",
    "ACCE_AC7_EXTREME_IQR_MULTIPLIER",
    "ACCE_AC7_MILD_IQR_MULTIPLIER",
    "ACCE_AC7_MIN_POPULATION",
    "ACCE_AC7_REQUIRED_COLUMNS",
    "ACCE_AC7_SEGMENT_BY_PROJECT_TYPE_PARAM",
    "ACCE_AC7_SEGMENT_REFERENCE",
    "ACCE_AC7_SEGMENT_REQUIRED_COLUMNS",
    "ACCE_AC7_THRESHOLD_CHOICES",
    "ACCE_AC7_THRESHOLD_PARAM",
    "ACCE_AC8_EXTREME_IQR_MULTIPLIER",
    "ACCE_AC8_MILD_IQR_MULTIPLIER",
    "ACCE_AC8_MIN_POPULATION",
    "ACCE_AC8_REQUIRED_COLUMNS",
    "ACCE_AC8_SEGMENT_BY_PROJECT_TYPE_PARAM",
    "ACCE_AC8_SEGMENT_REFERENCE",
    "ACCE_AC8_SEGMENT_REQUIRED_COLUMNS",
    "ACCE_AC8_THRESHOLD_CHOICES",
    "ACCE_AC8_THRESHOLD_PARAM",
    "check_acce_ac1",
    "check_acce_ac2",
    "check_acce_ac3",
    "check_acce_ac4",
    "check_acce_ac5",
    "check_acce_ac6",
    "check_acce_ac7",
    "check_acce_ac8",
    # SQS (Quality domain)
    "SQS_DQ_INSPECTION_12_COMPLETED_STATUS",
    "SQS_DQ_INSPECTION_12_REQUIRED_COLUMNS",
    "SQS_DQ_INSPECTION_13_REQUIRED_COLUMNS",
    "check_sqs_dq_inspection_12",
    "check_sqs_dq_inspection_13",
    # Private helpers retained because the test suite imports them directly.
    "_check_supports_params",
    "_coerce_threshold",
    "_is_filled",
    "_resolve_planview_segment_map",
    "_a1_value_valid",
    "_classify_a4_quantity",
    "_classify_a4_scope",
    "_classify_a8_category",
    "_resolve_coa_master_lookups",
    "_classify_ac4_quantity_acce",
    "_classify_ac4_scope_acce",
    "_classify_ac8_category_acce",
]
