"""Step 6: Scorecard dashboard - orchestration.

Runs the scorecard computation for each Data Product and renders the
per-DP dashboard card (gauge + tab row + export buttons) on top of a
cross-DP overview. The dashboard's pieces (CSS, exports, charts,
breakdown helpers, per-DP card) live in :mod:`ui.step_06` so each piece
stays small.

This module owns:

- the page header / overview row
- the ``render()`` entry point that iterates the scorecards
- the bottom navigation (Back / Restart / ML Lab)

It re-exports the helper symbols that tests (and the ML Lab) reach for
directly: ``_build_rowscores_csv``, ``_per_rule_score_columns``,
``_status_class``, ``_render_source_breakdown``.
"""
from __future__ import annotations

import logging

import streamlit as st

from config.settings import SETTINGS
from src.one_click import ONE_CLICK_SUMMARY_KEY
from src.scorecard import compute_scorecard
from ui.step_06._breakdown import (
    _render_custom_rules_table,
    _render_dp_card_header,
    _render_source_breakdown,
)
from ui.step_06._charts import _gauge, _threshold_bar
from ui.step_06._dp_dashboard import _render_dashboard_for_dp, _render_overview_cards
from ui.step_06._drilldown import (
    _render_cde_drilldown,
    _render_custom_rule_drilldown,
    _render_dimension_drilldown,
    _render_failing_rows,
    _render_rule_drilldown,
)
from ui.step_06._export import (
    _build_config_json,
    _build_rowscores_csv,
    _per_rule_score_columns,
    _reference_columns_for_export,
)
from ui.step_06._history import (
    _record_runs,
    _render_drop_alert,
    _render_history_tab,
)
from ui.step_06._shared import (
    _DEFAULT_ACCENT,
    _SYSTEM_ACCENTS,
    _SYSTEM_ICONS,
    _status_class,
)
from utils.helpers import section_header
from utils.session_state import goto, prev_step, restart_app
from utils.ui_components import render_restart_button

logger = logging.getLogger(__name__)


def _render_one_click_summary() -> None:
    """Render the one-time banner produced by a One-click run, if present.

    One-click stashes a summary (systems scored / skipped / warnings / CSV
    export errors) under ``ONE_CLICK_SUMMARY_KEY`` before landing here. It's
    purely informational and only shows for One-click runs; the Step-by-step flow
    never sets the key. The banner persists until Restart / domain switch
    (which clears the key) so it survives the dashboard's frequent reruns.
    """
    summary = st.session_state.get(ONE_CLICK_SUMMARY_KEY)
    if not summary:
        return
    scored = summary.get("scored", [])
    skipped = summary.get("skipped", {}) or {}
    warnings = summary.get("warnings", []) or []
    csv_errors = summary.get("csv_errors", {}) or {}

    scored_txt = ", ".join(f"`{c}`" for c in scored) or "none"
    st.success(
        f"⚡ **Generated by One-click** - scored {len(scored)} system(s): "
        f"{scored_txt}. All Custom DQRs applied at default settings with "
        "weights distributed equally. Export each Data Product below."
    )
    if skipped:
        lines = "\n".join(f"- **{c}**: {r}" for c, r in skipped.items())
        st.warning("⚠ Some systems were skipped:\n\n" + lines)
    if warnings:
        with st.expander(f"ℹ️ {len(warnings)} One-click note(s)", expanded=False):
            for w in warnings:
                st.markdown(f"- {w}")
    if csv_errors:
        lines = "\n".join(f"- **{c}**: {e}" for c, e in csv_errors.items())
        st.error("❌ CSV export could not be prepared for:\n\n" + lines)


def render() -> None:
    st.markdown('<div class="step-pill">Final step · Scorecard Dashboard</div>',
                unsafe_allow_html=True)
    section_header(
        "Step 6 - Scorecard Dashboard",
        "Final result: score per Data Product, threshold distribution, CDE and "
        "dimension breakdowns, pass rate for each DQR, and worst-row inspection.",
    )

    _render_one_click_summary()

    dps = st.session_state.data_products
    configs = st.session_state.configs

    # Compute / recompute on render to reflect any upstream changes. Include
    # DPs that selected only the Custom source (so cfg.assignments is empty)
    # but have ≥ 1 custom_assignments - ``compute_scorecard`` handles both.
    scorecards = {}
    failed: dict = {}
    with st.spinner("⚙️ Computing scorecards from the latest rules and weights..."):
        for code, dp in dps.items():
            cfg = configs[code]
            if not cfg.assignments and not cfg.custom_assignments:
                continue
            try:
                result = compute_scorecard(
                    dp, cfg,
                    threshold_green=SETTINGS.threshold_green,
                    threshold_yellow=SETTINGS.threshold_yellow,
                )
            except Exception as exc:
                # One bad Data Product must not blank the whole dashboard. Record
                # it, surface it below, and keep rendering the rest - mirroring the
                # per-system isolation One-click already does.
                logger.warning(
                    "Scorecard computation failed for %s; leaving it out",
                    code, exc_info=True,
                )
                failed[code] = str(exc)
                continue
            scorecards[code] = result
    st.session_state.scorecards = scorecards

    # Persist one run snapshot per DP (deduplicated inside) so the History
    # tab, the drop alert and the ML Lab Run History survive Restart.
    _record_runs(scorecards)

    if failed:
        lines = "\n".join(f"- **{c}**: {e}" for c, e in failed.items())
        st.error(
            "⚠️ Some Data Products could not be scored and were left out of "
            "the dashboard:\n\n" + lines
        )

    if not scorecards:
        if not failed:
            st.error("🚫 No Data Product with defined rules. Go back to the previous step.")
        _nav()
        return

    # Summary row across all DPs
    with st.container(border=True):
        st.markdown("### 🏁 Overview")
        if failed:
            n_failed = len(failed)
            st.caption(
                f"At-a-glance final scores across the {len(scorecards)} scored "
                f"Data Product(s); {n_failed} could not be scored and "
                f"{'is' if n_failed == 1 else 'are'} excluded (see the warning above)."
            )
        else:
            st.caption("At-a-glance final scores across every Data Product.")
        _render_overview_cards(scorecards)

    st.markdown("---")

    for code, result in scorecards.items():
        _render_dashboard_for_dp(code, dps[code], result)

    st.markdown("---")
    _nav()


def _nav() -> None:
    c1, c2, c3, c_mid = st.columns([1, 1, 2, 4])
    with c1:
        if st.button("⬅ Back", use_container_width=True):
            prev_step()
    with c2:
        render_restart_button(restart_app, key="restart_confirm_dashboard")
    with c3:
        if st.button(
            "🧪 ML Lab (beta)", use_container_width=True,
            key="dashboard_open_ml_lab",
            help="Open the experimental ML Lab - anomaly detection, "
                 "rule impact, CDE clustering, weight sensitivity. "
                 "Read-only; does not change any score or rule.",
        ):
            goto("ml_lab")
    with c_mid:
        st.markdown(
            "<div style='text-align: center; padding-top: 0.55em; "
            "color: rgba(49,51,63,0.6); font-size: 0.85em;'>"
            "✅ End of workflow - use the export buttons in each card to save "
            "the results, or restart to evaluate another configuration."
            "</div>",
            unsafe_allow_html=True,
        )


__all__ = [
    "render",
    # Public-ish helpers reached by tests, the ML Lab and other UI steps.
    "_build_config_json",
    "_build_rowscores_csv",
    "_per_rule_score_columns",
    "_reference_columns_for_export",
    "_status_class",
    "_render_source_breakdown",
    "_render_custom_rules_table",
    "_render_dp_card_header",
    "_render_dashboard_for_dp",
    "_render_overview_cards",
    "_render_cde_drilldown",
    "_render_dimension_drilldown",
    "_render_rule_drilldown",
    "_render_custom_rule_drilldown",
    "_render_failing_rows",
    "_record_runs",
    "_render_drop_alert",
    "_render_history_tab",
    "_gauge",
    "_threshold_bar",
    "_SYSTEM_ICONS",
    "_SYSTEM_ACCENTS",
    "_DEFAULT_ACCENT",
]
